# Generated by Django 5.1.4 on 2025-01-09 17:59

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cidade', models.CharField(max_length=255, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('gestor', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endereco'),
        ),
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Denuncia', 'Denúncia'), ('Ajuda', 'Ajuda'), ('Solicitacao', 'Solicitação'), ('Elogio', 'Elogio'), ('Sugestao', 'Sugestão'), ('Esclarecimento', 'Esclarecimento')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('Publico', 'Público'), ('Privado', 'Privado')], default='Publico', max_length=20, null=True)),
                ('conteudo', models.TextField(max_length=280)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('qtd_up', models.PositiveIntegerField(default=0)),
                ('qtd_down', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='manifestacao/', validators=[api.models.validate_imagem, api.models.validate_tamanho])),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes', to=settings.AUTH_USER_MODEL)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Publico', 'Público'), ('Privado', 'Privado')], default='Publico', max_length=20, null=True)),
                ('conteudo', models.TextField(max_length=25000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('qtd_up', models.PositiveIntegerField(default=0)),
                ('qtd_down', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagem/', validators=[api.models.validate_imagem, api.models.validate_tamanho])),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(max_length=280)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.manifestacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('prefeitura_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='api.prefeitura')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.usuario',),
        ),
    ]
