# Generated by Django 5.1.4 on 2025-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='auth0_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
