# Generated by Django 5.1.4 on 2024-12-27 14:13

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='secretaria',
        ),
        migrations.AddField(
            model_name='resposta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='manifestacao/', validators=[api.models.validate_imagem, api.models.validate_tamanho]),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='postagem/', validators=[api.models.validate_imagem, api.models.validate_tamanho]),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='manifestacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.manifestacao'),
        ),
    ]
