# Generated by Django 5.1.4 on 2025-01-13 00:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='auth0_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem_background',
            field=models.ImageField(blank=True, null=True, upload_to='background/', validators=[api.models.validate_imagem, api.models.validate_tamanho]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/', validators=[api.models.validate_imagem, api.models.validate_tamanho]),
        ),
    ]
