# Generated by Django 5.1.4 on 2025-01-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='cidadao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='manifestacao',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='orgao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='prefeitura',
            options={'ordering': ['cidade']},
        ),
        migrations.AlterModelOptions(
            name='resposta',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterField(
            model_name='manifestacao',
            name='conteudo',
            field=models.TextField(max_length=400),
        ),
    ]
