# Generated by Django 5.1.3 on 2024-11-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secretario', models.CharField(max_length=255)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SECRETARIA',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'ADMIN',
            },
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'M')], default='M', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endereco')),
            ],
            options={
                'db_table': 'CIDADAO',
            },
        ),
        migrations.CreateModel(
            name='Prefeitura',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('periodo_mandato', models.CharField(max_length=255)),
                ('gestor', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=17, unique=True)),
            ],
            options={
                'db_table': 'PREFEITURA',
            },
        ),
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('qtd_up', models.IntegerField()),
                ('qtd_down', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secretaria')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
            options={
                'db_table': 'MANIFESTACAO',
            },
        ),
        migrations.AddField(
            model_name='secretaria',
            name='prefeitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prefeitura'),
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('prefeitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prefeitura')),
            ],
            options={
                'db_table': 'POSTAGEM',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manifestacao')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secretaria')),
            ],
            options={
                'db_table': 'RESPOSTA',
                'unique_together': {('manifestacao', 'secretaria')},
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manifestacao')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
            options={
                'db_table': 'DENUNCIA',
                'unique_together': {('cidadao', 'manifestacao')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('manifestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manifestacao')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidadao')),
            ],
            options={
                'db_table': 'AVALIACAO',
                'unique_together': {('cidadao', 'manifestacao')},
            },
        ),
    ]
